#################################################
# Challenge part 2 - Initial Server Setup
# root
#################################################

- hosts: all
  remote_user: root
  vars_files:
    - vars/default.yml

# Install Packages
  tasks:
    - name: Install Prerequisites
      apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

    - name: Update apt
      apt: update_cache=yes

    - name: Install required system packages
      apt: name={{ sys_packages }} state=latest

