---
create_user: webserver
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ecdsa.pub') }}"
sys_packages: [ 'curl', 'vim', 'git', 'nginx', 'rsync' ]
domain: webserver.com
release_version: rc-0.0.3

#
# Unless the infrastructure has got some email services
# (such as postfix) without authentication to send a email,
# Credentials for an account must be filled.
#
email_crontab: "x@x"

smtp_server: "mx.smtp"
smtp_port: 587
email_from: "a@a"
email_to: "b@b"
email_subject: "Relatorio - Desafio parte 2"
email_login: "my login"
email_pass: "pass"
log_file: "/var/log/nginx/access_{{ domain }}.log"
